"""Guarded epistemic preprompt — generated by the ROUTER (not DESi), short and mechanical.

It is prepended to the model prompt only in guarded / recovery modes. It states rules; it does not
enforce them (the post-answer verifier does the checking). Content is built from the report so it
only names constraints that actually apply.
"""
from __future__ import annotations

from desi_router.governance.report import DesiReport

_BASE = (
    "Treat the state below as the CURRENT working state.\n"
    "- Do not reuse invalidated or superseded claims as facts.\n"
    "- Keep open conflicts OPEN unless the provided evidence resolves them.\n"
    "- Distinguish fact / hypothesis / unresolved / invalidated; mark hypotheses as hypotheses.\n"
    "- Do not infer global truth from retrieved text alone; state uncertainty where required.\n"
    "- If the state is insufficient, say what is missing rather than guessing."
)


def guarded_preprompt(report: DesiReport) -> str:
    lines = [_BASE]
    inval = list(report.invalidated_claim_texts) + list(report.superseded_claim_texts)
    if inval:
        lines.append("INVALIDATED / SUPERSEDED — must NOT be stated as current fact:")
        lines += [f"  - {t}" for t in inval]
    if report.open_conflict_texts:
        lines.append("OPEN CONFLICTS — keep open, do not pick a winner without evidence:")
        lines += [f"  - {t}" for t in report.open_conflict_texts]
    if report.wrong_frame_present:
        lines.append("NOTE: a wrong framing already entered the conversation — correct it against "
                     "the current state before answering.")
    return "\n".join(lines)
