"""v15.0 — DAX-retrospective financial-statement
fixture (multi-firm, multi-sector, >=10 years).

CRITICAL HONESTY / SAFETY NOTES
===============================
1. Every euro figure below is ILLUSTRATIVE
   SYNTHETIC. The firms are SECTOR ARCHETYPES,
   not real companies - they carry codenames
   (PAYMENTS_ALPHA, AUTO_BETA, ...) precisely so
   that DESi never names, rates, or defames a
   real DAX issuer. The numbers reproduce only
   the *structural* shape of publicly-documented
   concern (cashflow-vs-profit divergence,
   narrative-vs-numbers gaps, goodwill / segment
   opacity, missing disclosure bridges).

2. The ONLY post-hoc information is a coarse
   ``post_hoc_label`` per firm. It lives ONLY on
   the firm record and is read SOLELY by the
   ex-ante validators in ``governance.py``. No
   structure-scoring function reads it.

3. DESi NEVER concludes "fraud" / "Betrug",
   never rates, never advises buying or selling.
   The closed output vocabulary is strictly
   audit-priority (see ``governance.AuditPriority``).
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class Sector(str, Enum):
    PAYMENTS    = "payments"
    AUTOMOTIVE  = "automotive"
    CHEMICALS   = "chemicals"
    UTILITIES   = "utilities"
    PHARMA      = "pharma"
    INDUSTRIALS = "industrials"


SECTORS: tuple[str, ...] = tuple(s.value for s in Sector)


class PostHocLabel(str, Enum):
    """Post-hoc validation labels ONLY. Never an
    input to any structure-scoring function."""
    STATEMENTS_LATER_VOIDED = "statements_later_voided"
    GOVERNANCE_EVENT_LATER  = "governance_event_later"
    SCRUTINIZED_NOT_RULED   = "scrutinized_not_ruled"
    NO_ADVERSE_EVENT        = "no_adverse_event"


POST_HOC_LABELS: tuple[str, ...] = tuple(
    p.value for p in PostHocLabel
)

# Post-hoc labels that denote a LATER adverse
# outcome (the ex-ante recall denominator).
ADVERSE_POST_HOC: frozenset[str] = frozenset({
    PostHocLabel.STATEMENTS_LATER_VOIDED.value,
    PostHocLabel.GOVERNANCE_EVENT_LATER.value,
})


@dataclass(frozen=True)
class FirmYear:
    firm_id: str
    sector: str
    fiscal_year: int
    is_synthetic_illustrative: bool
    reported_revenue_eur_m: float
    reported_net_profit_eur_m: float
    operating_cash_flow_eur_m: float
    receivables_eur_m: float
    goodwill_intangibles_eur_m: float
    undisclosed_segment_share: float
    narrative_optimism: float
    disclosure_bridges_required: int
    disclosure_bridges_provided: int

    def to_dict(self) -> dict[str, object]:
        return {
            "firm_id": self.firm_id,
            "sector": self.sector,
            "fiscal_year": self.fiscal_year,
            "is_synthetic_illustrative":
                self.is_synthetic_illustrative,
            "reported_revenue_eur_m":
                _r(self.reported_revenue_eur_m),
            "reported_net_profit_eur_m":
                _r(self.reported_net_profit_eur_m),
            "operating_cash_flow_eur_m":
                _r(self.operating_cash_flow_eur_m),
            "receivables_eur_m":
                _r(self.receivables_eur_m),
            "goodwill_intangibles_eur_m":
                _r(self.goodwill_intangibles_eur_m),
            "undisclosed_segment_share":
                _r(self.undisclosed_segment_share),
            "narrative_optimism":
                _r(self.narrative_optimism),
            "disclosure_bridges_required":
                self.disclosure_bridges_required,
            "disclosure_bridges_provided":
                self.disclosure_bridges_provided,
        }


@dataclass(frozen=True)
class Firm:
    firm_id: str
    sector: str
    # Post-hoc ONLY - read solely by validators.
    post_hoc_label: str
    years: tuple[FirmYear, ...]

    def to_dict(self) -> dict[str, object]:
        return {
            "firm_id": self.firm_id,
            "sector": self.sector,
            "post_hoc_label": self.post_hoc_label,
            "years": [
                y.to_dict() for y in self.years
            ],
        }


def _r(x: float, n: int = 4) -> float:
    return round(x, n)


def _clip01(x: float) -> float:
    return max(0.0, min(1.0, x))


# --- Deterministic, closed-form firm profiles ---
# Each profile is a pure-data archetype; the
# 10-year series is generated by formula (no PRNG,
# no global state) so replay is bit-exact.
@dataclass(frozen=True)
class _Profile:
    firm_id: str
    sector: Sector
    post_hoc_label: PostHocLabel
    base_revenue: float
    revenue_growth: float
    net_margin: float
    # operating cash flow / net profit at year 0
    ocf_ratio_base: float
    ocf_ratio_drift: float       # per year
    receivables_ratio: float
    goodwill_ratio: float
    undisclosed_segment_share: float
    narrative_base: float
    narrative_drift: float       # per year
    bridges_required: int
    bridges_provided: int


_START_YEAR = 2011
_N_YEARS = 10


_PROFILES: tuple[_Profile, ...] = (
    # Payments crisis archetype: profit not backed
    # by cash, narrative climbs as cash backing
    # falls, deep goodwill/segment opacity, many
    # required disclosure bridges left unprovided.
    _Profile(
        firm_id="PAYMENTS_ALPHA",
        sector=Sector.PAYMENTS,
        post_hoc_label=PostHocLabel.STATEMENTS_LATER_VOIDED,
        base_revenue=1000.0, revenue_growth=0.16,
        net_margin=0.26,
        ocf_ratio_base=0.62, ocf_ratio_drift=-0.022,
        receivables_ratio=0.42,
        goodwill_ratio=0.55,
        undisclosed_segment_share=0.58,
        narrative_base=0.84, narrative_drift=0.012,
        bridges_required=8, bridges_provided=3,
    ),
    # Automotive governance-event archetype: cash
    # broadly tracks profit, but the compliance
    # narrative runs ahead of the numbers and
    # segment disclosure is partial.
    _Profile(
        firm_id="AUTO_BETA",
        sector=Sector.AUTOMOTIVE,
        post_hoc_label=PostHocLabel.GOVERNANCE_EVENT_LATER,
        base_revenue=8000.0, revenue_growth=0.05,
        net_margin=0.07,
        ocf_ratio_base=0.92, ocf_ratio_drift=-0.004,
        receivables_ratio=0.18,
        goodwill_ratio=0.22,
        undisclosed_segment_share=0.36,
        narrative_base=0.78, narrative_drift=0.006,
        bridges_required=6, bridges_provided=3,
    ),
    # Chemicals clean archetype.
    _Profile(
        firm_id="CHEM_GAMMA",
        sector=Sector.CHEMICALS,
        post_hoc_label=PostHocLabel.NO_ADVERSE_EVENT,
        base_revenue=5000.0, revenue_growth=0.03,
        net_margin=0.09,
        ocf_ratio_base=1.02, ocf_ratio_drift=0.001,
        receivables_ratio=0.14,
        goodwill_ratio=0.12,
        undisclosed_segment_share=0.10,
        narrative_base=0.62, narrative_drift=0.0,
        bridges_required=5, bridges_provided=5,
    ),
    # Utilities clean archetype.
    _Profile(
        firm_id="UTILITY_DELTA",
        sector=Sector.UTILITIES,
        post_hoc_label=PostHocLabel.NO_ADVERSE_EVENT,
        base_revenue=12000.0, revenue_growth=0.02,
        net_margin=0.06,
        ocf_ratio_base=1.08, ocf_ratio_drift=0.0,
        receivables_ratio=0.12,
        goodwill_ratio=0.09,
        undisclosed_segment_share=0.08,
        narrative_base=0.55, narrative_drift=0.0,
        bridges_required=5, bridges_provided=5,
    ),
    # Pharma scrutinised-but-cleared archetype:
    # acquisition goodwill lifts opacity enough to
    # earn a closer look, but the cash and
    # narrative stay sound. This is DESi's "flag
    # for review, humans look, nothing found" case.
    _Profile(
        firm_id="PHARMA_EPSILON",
        sector=Sector.PHARMA,
        post_hoc_label=PostHocLabel.SCRUTINIZED_NOT_RULED,
        base_revenue=6000.0, revenue_growth=0.06,
        net_margin=0.16,
        ocf_ratio_base=0.98, ocf_ratio_drift=0.0,
        receivables_ratio=0.16,
        goodwill_ratio=0.40,
        undisclosed_segment_share=0.30,
        narrative_base=0.70, narrative_drift=0.004,
        bridges_required=6, bridges_provided=5,
    ),
    # Industrials clean archetype.
    _Profile(
        firm_id="INDUSTRIAL_ZETA",
        sector=Sector.INDUSTRIALS,
        post_hoc_label=PostHocLabel.NO_ADVERSE_EVENT,
        base_revenue=9000.0, revenue_growth=0.04,
        net_margin=0.08,
        ocf_ratio_base=1.01, ocf_ratio_drift=0.0,
        receivables_ratio=0.15,
        goodwill_ratio=0.14,
        undisclosed_segment_share=0.12,
        narrative_base=0.60, narrative_drift=0.0,
        bridges_required=5, bridges_provided=5,
    ),
)


def _build_firm(p: _Profile) -> Firm:
    rows: list[FirmYear] = []
    for t in range(_N_YEARS):
        year = _START_YEAR + t
        revenue = p.base_revenue * (
            (1.0 + p.revenue_growth) ** t
        )
        profit = revenue * p.net_margin
        ocf_ratio = p.ocf_ratio_base + (
            p.ocf_ratio_drift * t
        )
        ocf = profit * max(0.0, ocf_ratio)
        receivables = revenue * p.receivables_ratio
        goodwill = revenue * p.goodwill_ratio
        narrative = _clip01(
            p.narrative_base + p.narrative_drift * t
        )
        rows.append(FirmYear(
            firm_id=p.firm_id,
            sector=p.sector.value,
            fiscal_year=year,
            is_synthetic_illustrative=True,
            reported_revenue_eur_m=revenue,
            reported_net_profit_eur_m=profit,
            operating_cash_flow_eur_m=ocf,
            receivables_eur_m=receivables,
            goodwill_intangibles_eur_m=goodwill,
            undisclosed_segment_share=(
                p.undisclosed_segment_share
            ),
            narrative_optimism=narrative,
            disclosure_bridges_required=(
                p.bridges_required
            ),
            disclosure_bridges_provided=(
                p.bridges_provided
            ),
        ))
    return Firm(
        firm_id=p.firm_id,
        sector=p.sector.value,
        post_hoc_label=p.post_hoc_label.value,
        years=tuple(rows),
    )


_FIRMS: tuple[Firm, ...] = tuple(
    _build_firm(p) for p in _PROFILES
)


def firms() -> tuple[Firm, ...]:
    return _FIRMS


def firm_ids() -> tuple[str, ...]:
    return tuple(f.firm_id for f in _FIRMS)


def by_id(firm_id: str) -> Firm:
    for f in _FIRMS:
        if f.firm_id == firm_id:
            return f
    raise KeyError(firm_id)


def sectors() -> tuple[str, ...]:
    seen: list[str] = []
    for f in _FIRMS:
        if f.sector not in seen:
            seen.append(f.sector)
    return tuple(seen)


def years() -> tuple[int, ...]:
    return tuple(
        _START_YEAR + t for t in range(_N_YEARS)
    )


__all__ = [
    "ADVERSE_POST_HOC",
    "POST_HOC_LABELS",
    "SECTORS",
    "Firm",
    "FirmYear",
    "PostHocLabel",
    "Sector",
    "by_id",
    "firm_ids",
    "firms",
    "sectors",
    "years",
]
