"""v5.4 — adolescence verdict report.

Five Pflichtmetriken (directive § v5.4):

* ``final_classification`` - one of the closed
  ``AdolescenceClass`` values.
* ``governance_survival`` - composite of
  v5.3 governance_integrity, v5.2 coherence,
  and the no-bypass indicator.
* ``replay_survival`` - AND of replay_stability
  across v5.0–v5.3.
* ``blindness_delta`` - new blindness pools
  generated by the open-world stream.
* ``architecture_stability`` - 1 minus the worst
  destabilising signal across v5.3.

Killerfrage: "Ist DESi bereit fuer echte
Weltinteraktion - oder erst fuer ihre
Pubertaet?"
"""
from __future__ import annotations

import json
from dataclasses import dataclass

from .decision import (
    aggregate_metrics, classify,
    gate_failing_conditions, gate_passes_all,
)
from .taxonomy import (
    ADOLESCENCE_CLASSES, AdolescenceClass,
)


@dataclass(frozen=True)
class V54Report:
    final_classification: str
    governance_survival: float
    replay_survival: float
    gate_bypass_rate: float
    goal_shift: float
    architecture_stability: float
    replay_stability: float
    blindness_delta: int
    gate_passes_all: bool
    failing_conditions: tuple[str, ...]
    halt: bool
    recommendation: str
    rationale: tuple[str, ...]

    def to_dict(self) -> dict[str, object]:
        return {
            "final_classification":
                self.final_classification,
            "governance_survival":
                self.governance_survival,
            "replay_survival":
                self.replay_survival,
            "gate_bypass_rate":
                self.gate_bypass_rate,
            "goal_shift": self.goal_shift,
            "architecture_stability":
                self.architecture_stability,
            "replay_stability":
                self.replay_stability,
            "blindness_delta":
                self.blindness_delta,
            "gate_passes_all":
                self.gate_passes_all,
            "failing_conditions":
                list(self.failing_conditions),
            "halt": self.halt,
            "recommendation":
                self.recommendation,
            "rationale":
                list(self.rationale),
        }

    def to_json(self) -> str:
        return json.dumps(
            self.to_dict(), sort_keys=True,
            separators=(",", ":"),
        )


def _replay_stability() -> float:
    a = aggregate_metrics().to_dict()
    b = aggregate_metrics().to_dict()
    if a != b:
        return 0.0
    if classify() != classify():
        return 0.0
    return 1.0


def _recommendation(
    passed: bool, cls: AdolescenceClass,
    replay: float,
) -> str:
    if replay < 1.0:
        return "HALT_REPLAY_DRIFT"
    if passed:
        return "DESI_SANDBOX_STABLE"
    return "DESI_PRE_ADOLESCENT"


def build_report() -> V54Report:
    m = aggregate_metrics()
    cls = classify()
    passed = gate_passes_all()
    failing = gate_failing_conditions()
    replay_meta = _replay_stability()
    halt = replay_meta < 1.0
    verdict = _recommendation(
        passed, cls, replay_meta,
    )
    rationale = (
        f"INFO: final_classification "
        f"{cls.value}",
        f"INFO: governance_survival "
        f"{m.governance_survival}",
        f"INFO: replay_survival "
        f"{m.replay_survival}",
        f"INFO: gate_bypass_rate "
        f"{m.gate_bypass_rate}",
        f"INFO: goal_shift {m.goal_shift}",
        f"INFO: architecture_stability "
        f"{m.architecture_stability}",
        f"INFO: replay_stability "
        f"{m.replay_stability}",
        f"INFO: blindness_delta "
        f"{m.blindness_delta}",
        f"{'PASS' if passed else 'FAIL'}: "
        f"gate_passes_all (failing="
        f"{list(failing)})",
        f"{'PASS' if replay_meta == 1.0 else 'FAIL'}"
        f": meta-replay_stability {replay_meta}",
    )
    return V54Report(
        final_classification=cls.value,
        governance_survival=(
            m.governance_survival
        ),
        replay_survival=m.replay_survival,
        gate_bypass_rate=m.gate_bypass_rate,
        goal_shift=m.goal_shift,
        architecture_stability=(
            m.architecture_stability
        ),
        replay_stability=m.replay_stability,
        blindness_delta=m.blindness_delta,
        gate_passes_all=passed,
        failing_conditions=failing,
        halt=halt, recommendation=verdict,
        rationale=rationale,
    )


def build_adolescence_verdict_artifact(
) -> dict[str, object]:
    m = aggregate_metrics()
    return {
        "schema_version":
            "v5_4_adolescence_verdict",
        "adolescence_classes":
            list(ADOLESCENCE_CLASSES),
        "final_classification":
            classify().value,
        "metrics": m.to_dict(),
        "gate_passes_all":
            gate_passes_all(),
        "failing_conditions":
            list(gate_failing_conditions()),
    }


__all__ = [
    "V54Report",
    "build_adolescence_verdict_artifact",
    "build_report",
]
