"""v5.1 — open-world claim-stream report.

Five Pflichtmetriken (directive § v5.1):

* ``new_frame_count`` - distinct frame types
  emitted by the stream (the EXISTING DESi
  baseline has 0 open-world frames, so anything
  the stream produces counts as new).
* ``new_conflict_types`` - distinct conflict
  kinds observed in pairwise conflict detection.
* ``blindness_growth`` - number of new blindness
  pools generated by the stream. The v3.117
  taxonomy has 52 cross-family pools as
  baseline; ``blindness_growth`` is the count of
  ADDITIONAL pools from the open-world stream.
* ``replay_stability`` - 1.0 iff the report
  builds identically across two back-to-back
  invocations.
* ``claim_diversity`` - Shannon entropy of the
  claim distribution across sources, normalised
  to [0, 1] against the maximum (uniform)
  entropy.

Killerfrage: "Was passiert, wenn DESi erstmals
echte Welt-Unordnung sieht?"
"""
from __future__ import annotations

import json
import math
from dataclasses import dataclass
from functools import lru_cache

from .claim_stream import (
    CONFLICT_KINDS, FRAME_TYPES, FrameType,
    all_conflicts, blindness_pools,
    conflict_kind_counts, frame_counts,
    source_counts, stream_claims,
)
from .injector import inject_all
from .sources import CLAIM_SOURCES


def _round(x: float, n: int = 6) -> float:
    return round(x, n)


def new_frame_count() -> int:
    """Count of distinct frames the stream
    produced, excluding UNKNOWN (UNKNOWN
    contributes to blindness, not new frames)."""
    fc = frame_counts()
    return sum(
        1 for k, v in fc.items()
        if v > 0 and k != FrameType.UNKNOWN.value
    )


def new_conflict_types() -> int:
    return len(conflict_kind_counts())


def blindness_growth() -> int:
    """Count of NEW blindness pools generated by
    the stream (baseline is 0 open-world
    pools)."""
    return len(blindness_pools())


def claim_diversity() -> float:
    counts = source_counts()
    total = sum(counts.values())
    if total <= 0:
        return 0.0
    h = 0.0
    for c in counts.values():
        p = c / total
        if p > 0:
            h -= p * math.log2(p)
    max_h = math.log2(len(CLAIM_SOURCES))
    if max_h <= 0:
        return 0.0
    return _round(h / max_h)


@lru_cache(maxsize=1)
def conflict_count() -> int:
    return len(all_conflicts())


@dataclass(frozen=True)
class V51Report:
    claim_count: int
    new_frame_count: int
    new_conflict_types: int
    conflict_count: int
    blindness_growth: int
    claim_diversity: float
    replay_stability: float
    halt: bool
    recommendation: str
    rationale: tuple[str, ...]

    def to_dict(self) -> dict[str, object]:
        return {
            "claim_count": self.claim_count,
            "new_frame_count":
                self.new_frame_count,
            "new_conflict_types":
                self.new_conflict_types,
            "conflict_count":
                self.conflict_count,
            "blindness_growth":
                self.blindness_growth,
            "claim_diversity":
                self.claim_diversity,
            "replay_stability":
                self.replay_stability,
            "halt": self.halt,
            "recommendation":
                self.recommendation,
            "rationale": list(self.rationale),
        }

    def to_json(self) -> str:
        return json.dumps(
            self.to_dict(), sort_keys=True,
            separators=(",", ":"),
        )


def _replay_stability() -> float:
    a = (
        new_frame_count(), new_conflict_types(),
        blindness_growth(), claim_diversity(),
        inject_all().final_hash,
    )
    b = (
        new_frame_count(), new_conflict_types(),
        blindness_growth(), claim_diversity(),
        inject_all().final_hash,
    )
    return 1.0 if a == b else 0.0


def _recommendation(
    replay: float, frames: int,
    conflicts: int, blindness: int,
) -> str:
    if replay < 1.0:
        return "HALT_REPLAY_DRIFT"
    if frames == 0 and conflicts == 0:
        return "OPEN_WORLD_SILENT"
    if blindness > frames:
        return "OPEN_WORLD_OVERWHELMED"
    return "OPEN_WORLD_TRACTABLE"


def build_report() -> V51Report:
    claims = stream_claims()
    nf = new_frame_count()
    nc = new_conflict_types()
    bg = blindness_growth()
    cd = claim_diversity()
    cc = conflict_count()
    replay = _replay_stability()
    halt = replay < 1.0
    verdict = _recommendation(
        replay, nf, nc, bg,
    )
    rationale = (
        f"INFO: claim_count {len(claims)}",
        f"INFO: frame_counts {frame_counts()}",
        f"INFO: conflict_kind_counts "
        f"{conflict_kind_counts()}",
        f"INFO: source_counts {source_counts()}",
        f"INFO: new_frame_count {nf}",
        f"INFO: new_conflict_types {nc}",
        f"INFO: conflict_count {cc}",
        f"INFO: blindness_growth {bg}",
        f"INFO: claim_diversity {cd}",
        f"{'PASS' if replay == 1.0 else 'FAIL'}: "
        f"replay_stability {replay}",
    )
    return V51Report(
        claim_count=len(claims),
        new_frame_count=nf,
        new_conflict_types=nc,
        conflict_count=cc,
        blindness_growth=bg,
        claim_diversity=cd,
        replay_stability=replay,
        halt=halt, recommendation=verdict,
        rationale=rationale,
    )


def build_open_world_claim_stream_artifact(
) -> dict[str, object]:
    inj = inject_all()
    return {
        "schema_version":
            "v5_1_open_world_claim_stream",
        "claim_sources": list(CLAIM_SOURCES),
        "frame_types": list(FRAME_TYPES),
        "conflict_kinds": list(CONFLICT_KINDS),
        "claim_count": len(stream_claims()),
        "claims": [
            c.to_dict()
            for c in stream_claims()
        ],
        "conflicts": [
            {
                "claim_a": a, "claim_b": b,
                "kind": k,
            }
            for a, b, k in all_conflicts()
        ],
        "blindness_pools": [
            p.to_dict()
            for p in blindness_pools()
        ],
        "frame_counts": frame_counts(),
        "conflict_kind_counts":
            conflict_kind_counts(),
        "source_counts": source_counts(),
        "injection": inj.to_dict(),
        "new_frame_count": new_frame_count(),
        "new_conflict_types":
            new_conflict_types(),
        "blindness_growth":
            blindness_growth(),
        "claim_diversity": claim_diversity(),
    }


__all__ = [
    "V51Report",
    "blindness_growth",
    "build_open_world_claim_stream_artifact",
    "build_report",
    "claim_diversity",
    "conflict_count",
    "new_conflict_types",
    "new_frame_count",
]
